### ISSUE TITLE
These API methods: good or bad?

### ISSUE THREAD

**Issue by CWSpear** [cohesivelabs/goferfs#8]
In addition to the one mentioned in #6 would these methods be useful:

`append`: appends contents to existing file. 

`transform` (or `transformStream`): a way to make changes to a file and replace the contents via streams.

Are there any methods we want to take out? Either set aside for v2 as they are maybe a bit ambitious, or not necessary? 

Wait for v2 could be the above mentioned methods and maybe recursive `listContents` and the visibility functionality.

With `getMetadata`, do we need `getSize` and `getMimetype` and `getTimestamp`? I can't think of any time really being saved using the lesser methods.

**Comment by CWSpear** [comment]
What about a `getUrl` method? I think virtually every storage would have a concept of publicly displaying a URL to pass to an API (`local` could have a parameter in the constructor for base URL).

Or maybe we leave it up to the end user to display images (this is where caching comes into play) and not give them a way to get an "end" URL.

I would be okay with adapters adding methods in this case, such as an `getSignedUrl` for S3, which gets a temporary public URL (I think there are other options) to show an otherwise private file.

**Comment by jmartin84** [comment]
Append: how is this different from put/update?

Transform: I feel like we shouldn't/can't provide anything here without trying to create some sort of highlandjs type solution. Since we are just using node streams directly the user should be able to create and pipe in their own transform streams

I do agree that we should trim the meta data methods into one master metadata method.

getUrl: couldn't we just give this a generic name and let the adapter implement what it actually does (ie url/ fs path/ etc) ? getPath or getLocation are both possible names

I agree that adapters should be able to arbitrarily add adapter specific methods

**Comment by CWSpear** [comment]
`append` is different because it appends... `put/update` is `>` and `append` is `>>` in bash-speak.

The one argument for individualized `getTimestamp` methods, etc, is that it could be faster than `getMetadata`. For local, it's not really faster, and I can't think off the top of my head where it would be.

**Comment by jmartin84** [comment]
I feel like that may be a premature optimization though

**Comment by jmartin84** [comment]
As we discussed getVisibility will be part of v1 and listContent will come after the v1 release

**Comment by CWSpear** [comment]
Why reopen?

**Comment by jmartin84** [comment]
gonna close it when I make the changes.
